In [2]:
import tensorflow as tf
from tensorflow import data
import multiprocessing
import numpy as np
import os


/home/asr/tensorflow-cpu/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/asr/tensorflow-cpu/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [3]:
def predictor(model_name):
    model_dir = os.path.join(os.getcwd(),'trained_models/{}'.format(MODEL_NAME))
    export_dir = model_dir +"/export/predict/"
    saved_model_dir= export_dir + "/" + os.listdir(path=export_dir)[-1]  
    return tf.contrib.predictor.from_saved_model(export_dir = saved_model_dir,signature_def_key="prediction")

In [30]:
#MDL_1 = 'stat-calendar_voc500+4500_mlen20_embs10_lay96-64-16_lr001_mystop'
#MDL_1 = 'cnn-test'
#MDL_2 = 'dyglove-calendar_voc5000+5000_mlen20_embs300_lay96-64-16_lr001_mystop'
#MDL_3 = 'dyglove-calendar_voc2500+2500_mlen20_embs300_lay96-64-16_lr001_mystop'
#MDL_4 = 'dyglove-calendar_voc13k+2k_mlen20_embs300_lay96-64-16_lr001_mystop_nodigits_humanized'
#MDL_5 = 'dyglove-calendar_voc5k+2k_mlen20_embs300_lay96-64-16_lr001_mystop_nodigits_humanized'
#MDL_5 = 'cnn-dyglove-calendar_voc7k+3k_mlen20_embs300_conv1d-fc64-32_lr001_mystop_nodigits_humanized'
#MDL_6 = 'dyglove-calendar_voc7k+3k_mlen20_embs300_lay96-64-16_lr001_mystop_nodigits_humanized'
#MDL_7 = 'dyglove-calendar_voc19k+1k_mlen20_embs300_lay96-64-16_lr001_mystop_nodigits_humanized'
#MDL_7 = 'cnn-dyglove-calendar_voc7k+3k_mlen20_embs300_conv1d-fc128-64_lr001_mystop_nodigits_humanized'
#MDL_7 = 'cnn-lstm-dyglove-calendar_voc7k+3k_mlen20_embs300_lay96-64-16_fc32-16_lr001_mystop_nodigits_humanized'
# The following is the best
#MDL_7 = 'cnn-dyglove-calendar_voc13k+2k_mlen20_embs300_conv1d-fc64-32_lr001_mystop_nodigits_humanized'
#MDL_4 = 'dyglove-calendar_voc15k+5k_mlen20_embs300_lay96-64-16_lr001_mystop'
#MDL_5 = 'dyglove-calendar_voc15k+5k_mlen20_embs300_lay96-64-16_lr001_mystop_nodigits'

output_dict = {"mdl1": predictor(MDL_1), "mdl2": predictor(MDL_2), "mdl3": predictor(MDL_3), "mdl4": predictor(MDL_4), "mdl5": predictor(MDL_5), "mdl6": predictor(MDL_6), "mdl7": predictor(MDL_7)}
#output_dict = {"mdl1": predictor(MDL_1), "mdl4": predictor(MDL_4), "mdl5": predictor(MDL_5)}


INFO:tensorflow:Restoring parameters from b'/home/asr/Data/classif_task/trained_models/cnn-test/export/predict//1536071851/variables/variables'
INFO:tensorflow:Restoring parameters from b'/home/asr/Data/classif_task/trained_models/dyglove-calendar_voc5000+5000_mlen20_embs300_lay96-64-16_lr001_mystop/export/predict//1534253762/variables/variables'
INFO:tensorflow:Restoring parameters from b'/home/asr/Data/classif_task/trained_models/dyglove-calendar_voc2500+2500_mlen20_embs300_lay96-64-16_lr001_mystop/export/predict//1534252221/variables/variables'
INFO:tensorflow:Restoring parameters from b'/home/asr/Data/classif_task/trained_models/dyglove-calendar_voc13k+2k_mlen20_embs300_lay96-64-16_lr001_mystop_nodigits_humanized/export/predict//1535705462/variables/variables'
INFO:tensorflow:Restoring parameters from b'/home/asr/Data/classif_task/trained_models/cnn-dyglove-calendar_voc7k+3k_mlen20_embs300_conv1d-fc64-32_lr001_mystop_nodigits_humanized/export/predict//1535989780/variables/variables

In [45]:
MDL_1 = 'lstm-dyglove_voc5k+2k_mlen20_lay96-64-16_lr001_mystop_nodigits_jsgf+subtitles+paisa'
MDL_2 = 'simple-cnn-dyglove_voc5k+2k_mlen20_conv1d-fc64-32_lr001_mystop_nodigits_jsgf+subtitles+paisa'
output_dict = {"mdl1": predictor(MDL_1), "mdl2": predictor(MDL_2)}

INFO:tensorflow:Restoring parameters from b'/home/asr/Data/classif_task/trained_models/lstm-dyglove_voc5k+2k_mlen20_lay96-64-16_lr001_mystop_nodigits_jsgf+subtitles+paisa/export/predict//1536154770/variables/variables'
INFO:tensorflow:Restoring parameters from b'/home/asr/Data/classif_task/trained_models/simple-cnn-dyglove_voc5k+2k_mlen20_conv1d-fc64-32_lr001_mystop_nodigits_jsgf+subtitles+paisa/export/predict//1536157508/variables/variables'


In [38]:
output = lambda mdl, sentence: output_dict[mdl]({'sentence':sentence})

In [46]:
sent = ['elimina tutti i vestiti', 'elimina tutti i problemi', 'elimina tutti gli appuntamenti']

print(np.around(output("mdl1", sent)['probabilities'][0:],decimals=3))
print("-------------")
print(np.around(output("mdl2", sent)['probabilities'][0:],decimals=3))
print("-------------")
# print(np.around(output("mdl3", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl4", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl5", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl6", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl7", sent)['probabilities'][0:],decimals=3))

# [1  0]
# [1  0]
# [0  1]

[[0.999 0.001]
 [0.999 0.001]
 [0.    1.   ]]
-------------
[[1.    0.   ]
 [1.    0.   ]
 [0.007 0.993]]
-------------


In [48]:
sent = ['ho un libro di storia sul comodino', 'segna domani gita in montagna sul calendario']

print(np.around(output("mdl1", sent)['probabilities'][0:],decimals=3))
print("-------------")
print(np.around(output("mdl2", sent)['probabilities'][0:],decimals=3))
print("-------------")
# print(np.around(output("mdl3", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl4", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl5", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl6", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl7", sent)['probabilities'][0:],decimals=3))

# [1  0]
# [0  1]

[[1. 0.]
 [0. 1.]]
-------------
[[1.   0.  ]
 [0.01 0.99]]
-------------


In [49]:
sent = ['ho visto sul calendario che domani è lunedì', 'puoi controllare l agenda', 'sarebbe carino creare una raccolta di programmi standalone da condividere']

print(np.around(output("mdl1", sent)['probabilities'][0:],decimals=3))
print("-------------")
print(np.around(output("mdl2", sent)['probabilities'][0:],decimals=3))
print("-------------")
# print(np.around(output("mdl3", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl4", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl5", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl6", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl7", sent)['probabilities'][0:],decimals=3))

# [0  1]
# [0  1]
# [0  1]

[[0.003 0.997]
 [0.    1.   ]
 [0.809 0.191]]
-------------
[[0.001 0.999]
 [0.006 0.994]
 [1.    0.   ]]
-------------


In [50]:
#sent = ['sfoglia il calendario', 'cosa facciamo questa settimana', 'ha un calendario appeso al muro']
sent = ['mi dici quali sono i miei programmi del mese per favore', 'dimmi i programmi del mese prossimo per favore', 'i miei programmi del mese']

print(np.around(output("mdl1", sent)['probabilities'][0:],decimals=3))
print("-------------")
print(np.around(output("mdl2", sent)['probabilities'][0:],decimals=3))
print("-------------")
# print(np.around(output("mdl3", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl4", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl5", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl6", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl7", sent)['probabilities'][0:],decimals=3))

# [0  1]
# [0  1]
# [0  1]

[[0.    1.   ]
 [0.    1.   ]
 [0.075 0.925]]
-------------
[[0.006 0.994]
 [0.001 0.999]
 [0.006 0.994]]
-------------


In [51]:
#sent = ['sulle impostazioni del calendario li ho spuntati ma anche aggiungendo la data']
sent = ['per favore aggiungi lunedì mattina spettacolo a teatro con marco sul calendario']

print(np.around(output("mdl1", sent)['probabilities'][0:],decimals=3))
print("-------------")
print(np.around(output("mdl2", sent)['probabilities'][0:],decimals=3))
print("-------------")
# print(np.around(output("mdl3", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl4", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl5", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl6", sent)['probabilities'][0:],decimals=3))
# print("-------------")
# print(np.around(output("mdl7", sent)['probabilities'][0:],decimals=3))

[[0. 1.]]
-------------
[[0. 1.]]
-------------
